name = "lyh-crisis-relations"
compatibility_date = "2024-09-14"
pages_build_output_dir = "out"

# D1 Database configuration - 默认绑定
[[d1_databases]]
binding = "DB"
database_name = "lyh-crisis-relations-db"
database_id = "ed0c5c5a-9eed-46ff-b9ed-a4a2aa144f75"  # 从您的截图中看到的实际 ID

[env.production.vars]
NODE_ENV = "production"
OPENAI_API_KEY = ""
OPENAI_BASE_URL = "https://api.moonshot.cn/v1"
OPENAI_MODEL = "kimi-k2-0905-preview"

[env.preview.vars]
NODE_ENV = "development"
OPENAI_API_KEY = ""
OPENAI_BASE_URL = "https://api.moonshot.cn/v1"
OPENAI_MODEL = "kimi-k2-0905-preview"