name = "lyh-crisis-relations"
compatibility_date = "2024-09-13"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

# D1 数据库配置
[[d1_databases]]
binding = "DB"
database_name = "lyh-crisis-relations-db"
database_id = "ed0c5c5a-9eed-46ff-b9c8-7e4b8c8e8e8e"

# Pages Functions 配置
[build]
command = "npm run build && npm run build:pages"
cwd = "."

[build.environment]
NODE_VERSION = "20"

# 环境变量
[vars]
NODE_ENV = "production"
OPENAI_API_KEY = "***REMOVED***"
OPENAI_BASE_URL = "https://api.moonshot.cn/v1"
OPENAI_MODEL = "kimi-k2-0905-preview"