# Cloudflare Pages 项目配置
name = "lyh-crisis-relations"

# D1 数据库配置
[[d1_databases]]
binding = "DB"
database_name = "lyh-crisis-relations-db"
database_id = "ed0c5c5a-9eed-46ff-b9ed-a4a2aa144f75"

# 环境变量（用于 Pages Functions）
[vars]
NODE_ENV = "production"
OPENAI_API_KEY = "***REMOVED***"
OPENAI_BASE_URL = "https://api.moonshot.cn/v1"
OPENAI_MODEL = "kimi-k2-0905-preview"